[build-system]
requires = ["setuptools>=61.0"]
build-backend = "setuptools.build_meta"

[project]
name = "beaker-pyteal"
authors = [
  { name="Ben Guidarelli", email="ben@algorand.com" },
]
description = "A Framework for building PyTeal Applications"
readme = "README.md"
license = { file="LICENSE" }
requires-python = ">=3.10"
dynamic = ["version"]
dependencies = [
  "py-algorand-sdk >= 1.16.1",
  "pyteal == 0.19.0"
]
classifiers = [
  "Development Status :: 2 - Pre-Alpha",
  "Programming Language :: Python :: 3.10",
  "License :: OSI Approved :: MIT License"
]

[tools.setuptools.dynamic]
version = {attr = "beaker-pyteal.VERSION"} 

[project.optional-dependencies]
tests = [
  "black==22.6.0",
  "pytest==7.1.2",
  "flake8==4.0.1",
  "mypy==0.971",
  "mypy-extensions==0.4.3",
]
docs = [
  "Sphinx==5.0.2",
  "sphinx-rtd-theme==1.0.0",
]



[project.urls]
"Homepage" = "https://beaker.algo.xyz"
"Bug Tracker" = "https://github.com/algorand-devrel/beaker/issues"